"""Guards against large blobs entering the tree (tuna-os/tromso#277).

A 67 MB `files/fakecap-manifest.tsv` was committed in May 2026 and removed
five days later. The removal reclaimed nothing: the blob is still in every
clone, and taking it out needs `git filter-repo` plus a force-push, which is
sequenced org-wide in tuna-os/tunaOS#2290.

Nothing stopped that add at the time — `.gitignore` already had a blanket
`files/` rule, and it was bypassed. So the guard has to live somewhere a
contributor cannot silently step around, which means CI.

Pure source inspection: no network, stdlib only (the CI pytest job installs
nothing but pytest).

See docs/adr/0005-fakecap-manifest-is-generated.md.
"""

import os
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# The org-wide scan in tuna-os/tunaOS#2290 flags blobs over 5 MB, so that is
# the bar here too. The largest tracked file today is
# files/mm-common/libstdc++.tag at 4.52 MiB, which leaves real but not
# generous headroom.
#
# If a legitimate build input crosses the line, add it here with its own
# ceiling rather than raising LIMIT for everything. A per-file ceiling still
# catches the case where an allowed file keeps growing.
LIMIT = 5 * 1024 * 1024
ALLOWANCES: dict[str, int] = {}

# Generated by another project's build, never a valid input here. See the ADR.
FAKECAP_MANIFEST = "files/fakecap-manifest.tsv"


def _tracked_files():
    """Repo-relative paths of everything git tracks, symlinks excluded."""
    out = subprocess.run(
        ["git", "-C", str(REPO), "ls-files", "-z"],
        capture_output=True,
        check=True,
        text=True,
    ).stdout
    return [p for p in out.split("\0") if p]


def _is_ignored(path):
    """True if .gitignore would keep `git add <path>` from working."""
    return (
        subprocess.run(
            ["git", "-C", str(REPO), "check-ignore", "-q", path],
            capture_output=True,
        ).returncode
        == 0
    )


TRACKED = _tracked_files()


def test_tracked_file_list_is_sane():
    """Guard the helper: if `git ls-files` returned nothing, every size
    assertion below would pass for the wrong reason."""
    assert len(TRACKED) > 500, len(TRACKED)
    assert "project.conf" in TRACKED


def test_no_tracked_blob_over_the_size_limit():
    """A large file costs every clone forever, because removing it later does
    not shrink history. Catch it before the commit, not after."""
    oversized = []
    for rel in TRACKED:
        path = REPO / rel
        if path.is_symlink() or not path.is_file():
            continue
        size = os.path.getsize(path)
        ceiling = ALLOWANCES.get(rel, LIMIT)
        if size > ceiling:
            oversized.append((size, rel, ceiling))

    oversized.sort(reverse=True)
    report = "\n".join(
        f"  {size / 1024 / 1024:.1f} MiB  {rel}  (limit {ceiling / 1024 / 1024:.1f} MiB)"
        for size, rel, ceiling in oversized
    )
    assert not oversized, (
        "tracked files over the size limit — generate them at build time, or "
        "add an explicit entry to ALLOWANCES with a reason:\n" + report
    )


def test_allowances_have_no_stale_entries():
    """Keep the ratchet honest: an entry for a file that shrank, moved or left
    the tree only hides the next regression."""
    stale = sorted(set(ALLOWANCES) - set(TRACKED))
    assert not stale, "ALLOWANCES entries that are no longer tracked:\n" + "\n".join(stale)


def test_fakecap_manifest_is_not_tracked():
    """The exact file from tuna-os/tromso#277. It is one project's build
    output, so re-adding it is always a mistake."""
    assert FAKECAP_MANIFEST not in TRACKED


def test_fakecap_manifest_stays_ignored():
    """`git add files/fakecap-manifest.tsv` must keep refusing, so a local
    chunkify run cannot sweep the manifest back in."""
    assert _is_ignored(FAKECAP_MANIFEST), (
        f"{FAKECAP_MANIFEST} is no longer covered by .gitignore"
    )


def test_build_input_trees_are_not_ignored():
    """`files/` and `patches/` hold real build inputs — `kind: local` sources
    and the freedesktop-sdk patch queue. A blanket ignore on them makes
    `git add` refuse a legitimate new input and hides it from `git status`,
    which is how files/fakecap/fakecap-restore.c stayed missing after the
    tromso-iso merge dropped it."""
    for probe in (
        "files/kde-linux-system/probe-not-a-real-file.conf",
        "patches/freedesktop-sdk/probe-not-a-real-file.patch",
    ):
        assert not _is_ignored(probe), (
            f"a .gitignore rule swallows {probe}; new build inputs under that "
            "tree cannot be added without `git add -f`"
        )
