kind: manual
description: Homebrew system files staged using Dakota's split pattern

sources:
- kind: git_repo
  url: github:ublue-os/brew.git
  track: main
  ref: 4576300de21e0ee3fc951895fe0e5edc04adf4cb

depends:
- freedesktop-sdk.bst:public-stacks/runtime-minimal.bst

variables:
  strip-binaries: ""

config:
  install-commands:
  - cp -r system_files/usr/ "%{install-root}%{prefix}/"
  - cp -r system_files/etc/ "%{install-root}%{sysconfdir}/"
  - "%{install-extra}"
