#!/usr/bin/env python3
"""Generate a build matrix for multi-runner CI.

Runs `bst show` to discover uncached elements, splits them into a core set
and N parallel chunks, and computes a composite cache key for each chunk.

Usage:
    python3 scripts/ci-build-matrix.py <target> <num_chunks> [core_split]

Output (JSON to stdout):
    {
      "core": "el1 el2 ...",
      "matrix": {"chunk1-name": "el3 el4 ...", ...},
      "cache_keys": {"chunk1-name": "sha256hex", ...},
      "final": "<target>"
    }
"""

import hashlib
import json
import subprocess
import sys


def get_build_plan(target: str, arch: str | None = None, plan_file: str | None = None) -> list[dict]:
    """Get elements that need building, with their full cache keys.

    If plan_file exists (pre-generated by the caller), parse it directly
    instead of invoking bst again — avoids needing to pass arch options.
    """
    import os
    if plan_file and os.path.exists(plan_file):
        with open(plan_file) as f:
            raw = f.read()
    else:
        cmd = ["bst"]
        if arch:
            cmd += ["-o", "arch", arch]
        cmd += [
            "show",
            "--deps", "all",
            "--order", "stage",
            "--format", "%{name}||%{state}||%{full-key}",
            target,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        raw = result.stdout

    elements = []
    for line in raw.splitlines():
        if not line.strip():
            continue
        try:
            parts = line.split("||")
            name = parts[0].strip()
            state = parts[1].strip()
            full_key = parts[2].strip() if len(parts) > 2 else ""
            if state != "cached":
                elements.append({"name": name, "state": state, "key": full_key})
        except (ValueError, IndexError):
            print(f"Skipping malformed line: {line}", file=sys.stderr)

    return elements


def chunk_list(data: list, num_chunks: int) -> list[list]:
    """Split data into N chunks using round-robin distribution."""
    return [data[i::num_chunks] for i in range(num_chunks)]


def make_chunk_name(index: int, elements: list[dict]) -> str:
    """Generate a descriptive chunk name from the first element."""
    if not elements:
        return f"chunk{index}"
    first = elements[0]["name"]
    # Extract a short label from the element name
    label = first.rsplit("/", 1)[-1].replace(".bst", "")
    return f"chunk{index}-{label}"


def compute_cache_key(elements: list[dict]) -> str:
    """Compute a composite cache key for a list of elements."""
    keys = sorted(e["key"] for e in elements if e["key"])
    if not keys:
        return ""
    combined = "\n".join(keys)
    return hashlib.sha256(combined.encode()).hexdigest()


def main():
    import os
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <target> <num_chunks> [core_split] [--arch ARCH]", file=sys.stderr)
        sys.exit(1)

    target = sys.argv[1]
    num_chunks = int(sys.argv[2])
    core_split = int(sys.argv[3]) if len(sys.argv) > 3 else 200
    arch = os.environ.get("BST_ARCH")

    # Use pre-generated build-plan.txt if present (avoids re-running bst show)
    plan_file = os.path.join(os.getcwd(), "build-plan.txt")
    elements = get_build_plan(target, arch=arch, plan_file=plan_file)
    print(f"Found {len(elements)} elements to build", file=sys.stderr)

    if not elements:
        # Nothing to build -- emit empty matrix
        result = {
            "core": "",
            "matrix": {},
            "cache_keys": {},
            "final": target,
        }
        print(json.dumps(result))
        return

    # Split into core (first N elements, which are foundational deps)
    # and leaves (everything else, parallelised across chunks)
    core_elements = elements[:core_split]
    leaf_elements = elements[core_split:]

    # Exclude the final target from chunks — it is built exclusively in
    # build_final so that the chunk jobs never need to archive a huge CAS
    # containing the full disk image artifact.
    leaf_elements_for_chunks = [e for e in leaf_elements if e["name"] != target]

    # Core targets as a space-separated string
    core_targets = " ".join(e["name"] for e in core_elements)

    # Split leaves into chunks
    if leaf_elements_for_chunks and num_chunks > 0:
        chunks = chunk_list(leaf_elements_for_chunks, min(num_chunks, len(leaf_elements_for_chunks)))
    else:
        chunks = []

    # Build the matrix
    matrix = {}
    cache_keys = {}
    for i, chunk in enumerate(chunks):
        if not chunk:
            continue
        name = make_chunk_name(i, chunk)
        matrix[name] = " ".join(e["name"] for e in chunk)
        key = compute_cache_key(chunk)
        if key:
            cache_keys[name] = key

    result = {
        "core": core_targets,
        "matrix": matrix,
        "cache_keys": cache_keys,
        "final": target,
    }

    print(json.dumps(result))


if __name__ == "__main__":
    main()
